Start = """
Привет %s!
Этот бот позволяет предложить стримеру хайлайт.
Для предложения хайлайта просто напиши его краткое описание, прямо во время стрима. _(например "Рофлы над потреблением памяти фреймворком QML")_
Пожалуйста не пиши сюда личные сообщения.
Бот сохраняет твои предложения в своей базе данных, позже стример может соотнести их с VOD-ами.
*Доступные комманды:*
/start - перезапуск
/stat - статистика
"""

Thanks = "%v, спасибо за предложение хайлайта! ❤"

Stat = """
Всего предложенно хайлайтов: %v
Предложенных тобой хайлайтов: %v
Uptime бота: %v
"""

CommandNotFound = "Неизвестная комманда!"

Spam = "Превышенно максимальное количество хайлайтов в час, попробуйте позже!"

Nothing = "Ничего не найдено!"

ChooseMounth = "Выбери месяц для просмотра:"

NewFrom = "Новый хайлайт от [\"%v\", %v]: \"%v\""
